### ISSUE TITLE
pylint score

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-4-documentation-and-style-nghitrampham#1]
Your code should get at score of at least 8 from pylint, but your code as a score of 2.81, mostly due to minor style issues.

[-2 points]

**Comment by nghitrampham** [comment]
Hi Daniel,


Can I redo the pylint again? And still get full score as mentioned in the class?

Thank you!!!
Tram

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nghitrampham** [comment]
Hi Daniel,

I updated HW4 to get pylint score> 8

Thank you!

Tram

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dcjones** [comment]
Looks good, 7/7 points.
